'------------------------------------------------------------------------------
' <auto-generated>
'     Il codice è stato generato da uno strumento.
'     Versione runtime:4.0.30319.42000
'
'     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
'     il codice viene rigenerato.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    'tramite uno strumento quale ResGen o Visual Studio.
    'Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    'con l'opzione /str oppure ricompilare il progetto VS.
    '''<summary>
    '''  Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("PDFView.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        '''  ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a &lt;HTML&gt;
        '''&lt;HEAD&gt;
        '''&lt;TITLE&gt;PageIndex&lt;/TITLE&gt;
        '''&lt;SCRIPT LANGUAGE=&quot;JavaScript&quot;&gt;
        '''function changeImage(filename)
        '''{
        '''  parent.pageviewer.document.images[&apos;mainimage&apos;].src = filename;
        '''}
        '''&lt;/script&gt;
        '''&lt;/HEAD&gt;
        '''&lt;BODY bgcolor=&quot;#DDDDDD&quot;&gt;{Body}&lt;/BODY&gt;
        '''&lt;/HTML&gt;.
        '''</summary>
        Friend ReadOnly Property BookmarkHtml() As String
            Get
                Return ResourceManager.GetString("BookmarkHtml", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a &lt;HTML&gt;
        '''&lt;HEAD&gt;
        '''&lt;TITLE&gt;PDF to Image Html&lt;/TITLE&gt;
        '''&lt;/HEAD&gt;
        '''&lt;FRAMESET ROWS=&quot;50,*&quot; FRAMEBORDER=0 BORDER=0 &gt;
        '''                        &lt;FRAME NAME=&quot;top&quot; SRC=&quot;content/top.html&quot; MARGINHEIGHT=0 MARGINWIDTH=0 NORESIZE&gt;
        '''            &lt;FRAMESET COLS=&quot;20%,80%&quot; FRAMEBORDER=0 BORDER=0&gt;
        '''                        &lt;FRAME NAME=&quot;left&quot; SRC=&quot;content/bookmark.html&quot; MARGINHEIGHT=0 MARGINWIDTH=0 SCROLLING=AUTO NORESIZE&gt;
        '''                        &lt;FRAMESET ROWS=&quot;*,25&quot; FRAMEBORDER=0 BORDER=0 &gt;
        '''                        	&lt;FRAME NAME=&quot;pa [stringa troncata]&quot;;.
        '''</summary>
        Friend ReadOnly Property FrameHtml() As String
            Get
                Return ResourceManager.GetString("FrameHtml", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a &lt;HTML&gt;
        '''&lt;HEAD&gt;
        '''&lt;TITLE&gt;PageViewer&lt;/TITLE&gt;
        '''&lt;/HEAD&gt;
        '''&lt;BODY bgcolor=&quot;#999999&quot;&gt;&lt;center&gt;&lt;img id=&quot;mainimage&quot; src=&quot;images/page1.png&quot; width=&quot;100%&quot;&gt;&lt;/center&gt;&lt;/BODY&gt;
        '''&lt;/HTML&gt;.
        '''</summary>
        Friend ReadOnly Property PageHtml() As String
            Get
                Return ResourceManager.GetString("PageHtml", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a &lt;HTML&gt;
        '''&lt;HEAD&gt;
        '''&lt;TITLE&gt;PageSize&lt;/TITLE&gt;
        '''&lt;SCRIPT LANGUAGE=&quot;JavaScript&quot;&gt;
        '''function fitScreen()
        '''{
        '''parent.pageviewer.document.images[&apos;mainimage&apos;].style.height = &apos;100%&apos;;
        '''parent.pageviewer.document.images[&apos;mainimage&apos;].style.width = &apos;auto&apos;;
        '''}
        '''function fitWidth()
        '''{
        '''parent.pageviewer.document.images[&apos;mainimage&apos;].style.height = &apos;auto&apos;;
        '''parent.pageviewer.document.images[&apos;mainimage&apos;].style.width = &apos;100%&apos;;
        '''}
        '''function fitActual()
        '''{
        '''parent.pageviewer.document.images[&apos;mainimage&apos;].style.height = &apos;auto&apos;;
        '''parent [stringa troncata]&quot;;.
        '''</summary>
        Friend ReadOnly Property PagesizeHtml() As String
            Get
                Return ResourceManager.GetString("PagesizeHtml", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a &lt;HTML&gt;
        '''&lt;HEAD&gt;
        '''&lt;TITLE&gt;DocumentName&lt;/TITLE&gt;
        '''&lt;/HEAD&gt;
        '''&lt;BODY bgcolor=&quot;#BBBBBB&quot;&gt;{DocumentName}&lt;/BODY&gt;
        '''&lt;/HTML&gt;.
        '''</summary>
        Friend ReadOnly Property TopHtml() As String
            Get
                Return ResourceManager.GetString("TopHtml", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
